EXCLUSION_CRITERIA_NODE = "exclusion_criteria_node"
OUT_SCOPE_MANAGE_NODE = "out_scope_manage_node"
TRADUCE_QUERY_NODE = "traduce_query_node"
CLASSIFY_LEVEL_NODE = "classify_level_node"
ASSIGN_LLM_NODE = "assing_llm_node"
REASONING_NODE = "reasoning_node"
SELECT_IMAGE_NODE = "select_image_node"
RAG_NODE = "rag_node"
TRADUCE_ORIGINALLANGUAGE_NODE = "traduce_original_language"

